// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cdprocessor.proto

package cdprocessor

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/recordcollection/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRippedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRippedRequest) Reset()         { *m = GetRippedRequest{} }
func (m *GetRippedRequest) String() string { return proto.CompactTextString(m) }
func (*GetRippedRequest) ProtoMessage()    {}
func (*GetRippedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{0}
}

func (m *GetRippedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRippedRequest.Unmarshal(m, b)
}
func (m *GetRippedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRippedRequest.Marshal(b, m, deterministic)
}
func (m *GetRippedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRippedRequest.Merge(m, src)
}
func (m *GetRippedRequest) XXX_Size() int {
	return xxx_messageInfo_GetRippedRequest.Size(m)
}
func (m *GetRippedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRippedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRippedRequest proto.InternalMessageInfo

type Track struct {
	TrackNumber          int32    `protobuf:"varint,1,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	WavPath              string   `protobuf:"bytes,2,opt,name=wav_path,json=wavPath,proto3" json:"wav_path,omitempty"`
	Mp3Path              string   `protobuf:"bytes,3,opt,name=mp3_path,json=mp3Path,proto3" json:"mp3_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{1}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetTrackNumber() int32 {
	if m != nil {
		return m.TrackNumber
	}
	return 0
}

func (m *Track) GetWavPath() string {
	if m != nil {
		return m.WavPath
	}
	return ""
}

func (m *Track) GetMp3Path() string {
	if m != nil {
		return m.Mp3Path
	}
	return ""
}

type Rip struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Tracks               []*Track `protobuf:"bytes,3,rep,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rip) Reset()         { *m = Rip{} }
func (m *Rip) String() string { return proto.CompactTextString(m) }
func (*Rip) ProtoMessage()    {}
func (*Rip) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{2}
}

func (m *Rip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rip.Unmarshal(m, b)
}
func (m *Rip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rip.Marshal(b, m, deterministic)
}
func (m *Rip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rip.Merge(m, src)
}
func (m *Rip) XXX_Size() int {
	return xxx_messageInfo_Rip.Size(m)
}
func (m *Rip) XXX_DiscardUnknown() {
	xxx_messageInfo_Rip.DiscardUnknown(m)
}

var xxx_messageInfo_Rip proto.InternalMessageInfo

func (m *Rip) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rip) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Rip) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type GetRippedResponse struct {
	Ripped               []*Rip   `protobuf:"bytes,1,rep,name=ripped,proto3" json:"ripped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRippedResponse) Reset()         { *m = GetRippedResponse{} }
func (m *GetRippedResponse) String() string { return proto.CompactTextString(m) }
func (*GetRippedResponse) ProtoMessage()    {}
func (*GetRippedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{3}
}

func (m *GetRippedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRippedResponse.Unmarshal(m, b)
}
func (m *GetRippedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRippedResponse.Marshal(b, m, deterministic)
}
func (m *GetRippedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRippedResponse.Merge(m, src)
}
func (m *GetRippedResponse) XXX_Size() int {
	return xxx_messageInfo_GetRippedResponse.Size(m)
}
func (m *GetRippedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRippedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRippedResponse proto.InternalMessageInfo

func (m *GetRippedResponse) GetRipped() []*Rip {
	if m != nil {
		return m.Ripped
	}
	return nil
}

type GetMissingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMissingRequest) Reset()         { *m = GetMissingRequest{} }
func (m *GetMissingRequest) String() string { return proto.CompactTextString(m) }
func (*GetMissingRequest) ProtoMessage()    {}
func (*GetMissingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{4}
}

func (m *GetMissingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMissingRequest.Unmarshal(m, b)
}
func (m *GetMissingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMissingRequest.Marshal(b, m, deterministic)
}
func (m *GetMissingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMissingRequest.Merge(m, src)
}
func (m *GetMissingRequest) XXX_Size() int {
	return xxx_messageInfo_GetMissingRequest.Size(m)
}
func (m *GetMissingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMissingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMissingRequest proto.InternalMessageInfo

type GetMissingResponse struct {
	Missing              []*proto1.Record `protobuf:"bytes,1,rep,name=missing,proto3" json:"missing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetMissingResponse) Reset()         { *m = GetMissingResponse{} }
func (m *GetMissingResponse) String() string { return proto.CompactTextString(m) }
func (*GetMissingResponse) ProtoMessage()    {}
func (*GetMissingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{5}
}

func (m *GetMissingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMissingResponse.Unmarshal(m, b)
}
func (m *GetMissingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMissingResponse.Marshal(b, m, deterministic)
}
func (m *GetMissingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMissingResponse.Merge(m, src)
}
func (m *GetMissingResponse) XXX_Size() int {
	return xxx_messageInfo_GetMissingResponse.Size(m)
}
func (m *GetMissingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMissingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMissingResponse proto.InternalMessageInfo

func (m *GetMissingResponse) GetMissing() []*proto1.Record {
	if m != nil {
		return m.Missing
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRippedRequest)(nil), "cdprocessor.GetRippedRequest")
	proto.RegisterType((*Track)(nil), "cdprocessor.Track")
	proto.RegisterType((*Rip)(nil), "cdprocessor.Rip")
	proto.RegisterType((*GetRippedResponse)(nil), "cdprocessor.GetRippedResponse")
	proto.RegisterType((*GetMissingRequest)(nil), "cdprocessor.GetMissingRequest")
	proto.RegisterType((*GetMissingResponse)(nil), "cdprocessor.GetMissingResponse")
}

func init() { proto.RegisterFile("cdprocessor.proto", fileDescriptor_f8eb0231462381e4) }

var fileDescriptor_f8eb0231462381e4 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0x53, 0xfa, 0x07, 0xfe, 0x4c, 0x8d, 0x81, 0xf1, 0x52, 0x49, 0x54, 0xec, 0xa9, 0xf1,
	0x50, 0x12, 0x38, 0x7b, 0x52, 0xa3, 0x31, 0xc1, 0x90, 0x8d, 0x9e, 0xb1, 0xdd, 0x6e, 0xe8, 0x46,
	0xda, 0x5d, 0x77, 0x17, 0xf8, 0x4a, 0x7e, 0x4c, 0xc3, 0xb6, 0x68, 0xb1, 0xe1, 0xb6, 0x79, 0x6f,
	0xe6, 0x37, 0x6f, 0xa6, 0x85, 0x01, 0x4d, 0xa5, 0x12, 0x94, 0x69, 0x2d, 0x54, 0x24, 0x95, 0x30,
	0x02, 0xbd, 0x9a, 0x34, 0x7c, 0x58, 0x72, 0x93, 0xad, 0x93, 0x88, 0x8a, 0x7c, 0x9c, 0x28, 0x61,
	0x32, 0xa6, 0x56, 0x62, 0xc9, 0xe9, 0x58, 0x31, 0x2a, 0x54, 0x4a, 0xc5, 0x6a, 0xc5, 0xa8, 0xe1,
	0xa2, 0x18, 0xdb, 0xe6, 0x86, 0x5c, 0x32, 0x03, 0x84, 0xfe, 0x23, 0x33, 0x84, 0x4b, 0xc9, 0x52,
	0xc2, 0x3e, 0xd7, 0x4c, 0x9b, 0xe0, 0x1d, 0xda, 0xaf, 0x2a, 0xa6, 0x1f, 0x78, 0x0d, 0x27, 0x66,
	0xf7, 0x58, 0x14, 0xeb, 0x3c, 0x61, 0xca, 0x77, 0x46, 0x4e, 0xd8, 0x26, 0x9e, 0xd5, 0x5e, 0xac,
	0x84, 0xe7, 0xf0, 0x7f, 0x1b, 0x6f, 0x16, 0x32, 0x36, 0x99, 0xdf, 0x1a, 0x39, 0x61, 0x8f, 0x74,
	0xb7, 0xf1, 0x66, 0x1e, 0x9b, 0x6c, 0x67, 0xe5, 0x72, 0x5a, 0x5a, 0x6e, 0x69, 0xe5, 0x72, 0xba,
	0xb3, 0x82, 0x37, 0x70, 0x09, 0x97, 0x78, 0x0a, 0x2d, 0x9e, 0x56, 0xd4, 0x16, 0x4f, 0x11, 0xe1,
	0x5f, 0x0d, 0x64, 0xdf, 0x78, 0x03, 0x1d, 0x3b, 0x4f, 0xfb, 0xee, 0xc8, 0x0d, 0xbd, 0x09, 0x46,
	0xf5, 0xc3, 0xd8, 0x9c, 0xa4, 0xaa, 0x08, 0x6e, 0x61, 0x50, 0x5b, 0x46, 0x4b, 0x51, 0x68, 0x86,
	0x21, 0x74, 0x94, 0x55, 0x7c, 0xc7, 0x02, 0xfa, 0x07, 0x00, 0xc2, 0x25, 0xa9, 0xfc, 0xe0, 0xcc,
	0xb6, 0xcf, 0xb8, 0xd6, 0xbc, 0x58, 0xee, 0x8f, 0xf1, 0x04, 0x58, 0x17, 0x2b, 0xe8, 0x04, 0xba,
	0x79, 0x29, 0x55, 0x54, 0x3f, 0x6a, 0x1c, 0x98, 0x58, 0x81, 0xec, 0x0b, 0x27, 0x5f, 0x0e, 0x78,
	0x77, 0xf7, 0xf3, 0xfd, 0x68, 0x7c, 0x86, 0xde, 0x4f, 0x5a, 0xbc, 0x38, 0x48, 0xf5, 0xf7, 0x93,
	0x0c, 0x2f, 0x8f, 0xd9, 0x55, 0x9e, 0x19, 0xc0, 0x6f, 0x4a, 0x6c, 0x54, 0x1f, 0xee, 0x34, 0xbc,
	0x3a, 0xea, 0x97, 0xb8, 0xa4, 0x63, 0x7f, 0x8e, 0xe9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x26, 0x1f, 0xf4, 0x85, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CDProcessorClient is the client API for CDProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CDProcessorClient interface {
	GetRipped(ctx context.Context, in *GetRippedRequest, opts ...grpc.CallOption) (*GetRippedResponse, error)
	GetMissing(ctx context.Context, in *GetMissingRequest, opts ...grpc.CallOption) (*GetMissingResponse, error)
}

type cDProcessorClient struct {
	cc *grpc.ClientConn
}

func NewCDProcessorClient(cc *grpc.ClientConn) CDProcessorClient {
	return &cDProcessorClient{cc}
}

func (c *cDProcessorClient) GetRipped(ctx context.Context, in *GetRippedRequest, opts ...grpc.CallOption) (*GetRippedResponse, error) {
	out := new(GetRippedResponse)
	err := c.cc.Invoke(ctx, "/cdprocessor.CDProcessor/GetRipped", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDProcessorClient) GetMissing(ctx context.Context, in *GetMissingRequest, opts ...grpc.CallOption) (*GetMissingResponse, error) {
	out := new(GetMissingResponse)
	err := c.cc.Invoke(ctx, "/cdprocessor.CDProcessor/GetMissing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDProcessorServer is the server API for CDProcessor service.
type CDProcessorServer interface {
	GetRipped(context.Context, *GetRippedRequest) (*GetRippedResponse, error)
	GetMissing(context.Context, *GetMissingRequest) (*GetMissingResponse, error)
}

func RegisterCDProcessorServer(s *grpc.Server, srv CDProcessorServer) {
	s.RegisterService(&_CDProcessor_serviceDesc, srv)
}

func _CDProcessor_GetRipped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRippedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDProcessorServer).GetRipped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdprocessor.CDProcessor/GetRipped",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDProcessorServer).GetRipped(ctx, req.(*GetRippedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDProcessor_GetMissing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMissingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDProcessorServer).GetMissing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdprocessor.CDProcessor/GetMissing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDProcessorServer).GetMissing(ctx, req.(*GetMissingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CDProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdprocessor.CDProcessor",
	HandlerType: (*CDProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRipped",
			Handler:    _CDProcessor_GetRipped_Handler,
		},
		{
			MethodName: "GetMissing",
			Handler:    _CDProcessor_GetMissing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdprocessor.proto",
}
