// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cdprocessor.proto

package cdprocessor

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/recordcollection/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ForceRequest_ForceType int32

const (
	ForceRequest_UNKNOWN        ForceRequest_ForceType = 0
	ForceRequest_RECREATE_LINKS ForceRequest_ForceType = 1
)

var ForceRequest_ForceType_name = map[int32]string{
	0: "UNKNOWN",
	1: "RECREATE_LINKS",
}

var ForceRequest_ForceType_value = map[string]int32{
	"UNKNOWN":        0,
	"RECREATE_LINKS": 1,
}

func (x ForceRequest_ForceType) String() string {
	return proto.EnumName(ForceRequest_ForceType_name, int32(x))
}

func (ForceRequest_ForceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{7, 0}
}

type Config struct {
	LastProcessTime      map[int32]int64 `protobuf:"bytes,1,rep,name=last_process_time,json=lastProcessTime,proto3" json:"last_process_time,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastProcessTime() map[int32]int64 {
	if m != nil {
		return m.LastProcessTime
	}
	return nil
}

type GetRippedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRippedRequest) Reset()         { *m = GetRippedRequest{} }
func (m *GetRippedRequest) String() string { return proto.CompactTextString(m) }
func (*GetRippedRequest) ProtoMessage()    {}
func (*GetRippedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{1}
}

func (m *GetRippedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRippedRequest.Unmarshal(m, b)
}
func (m *GetRippedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRippedRequest.Marshal(b, m, deterministic)
}
func (m *GetRippedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRippedRequest.Merge(m, src)
}
func (m *GetRippedRequest) XXX_Size() int {
	return xxx_messageInfo_GetRippedRequest.Size(m)
}
func (m *GetRippedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRippedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRippedRequest proto.InternalMessageInfo

type Track struct {
	Disk                 int32    `protobuf:"varint,5,opt,name=disk,proto3" json:"disk,omitempty"`
	TrackNumber          int32    `protobuf:"varint,1,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	WavPath              string   `protobuf:"bytes,2,opt,name=wav_path,json=wavPath,proto3" json:"wav_path,omitempty"`
	Mp3Path              string   `protobuf:"bytes,3,opt,name=mp3_path,json=mp3Path,proto3" json:"mp3_path,omitempty"`
	FlacPath             string   `protobuf:"bytes,4,opt,name=flac_path,json=flacPath,proto3" json:"flac_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{2}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetDisk() int32 {
	if m != nil {
		return m.Disk
	}
	return 0
}

func (m *Track) GetTrackNumber() int32 {
	if m != nil {
		return m.TrackNumber
	}
	return 0
}

func (m *Track) GetWavPath() string {
	if m != nil {
		return m.WavPath
	}
	return ""
}

func (m *Track) GetMp3Path() string {
	if m != nil {
		return m.Mp3Path
	}
	return ""
}

func (m *Track) GetFlacPath() string {
	if m != nil {
		return m.FlacPath
	}
	return ""
}

type Rip struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Tracks               []*Track `protobuf:"bytes,3,rep,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rip) Reset()         { *m = Rip{} }
func (m *Rip) String() string { return proto.CompactTextString(m) }
func (*Rip) ProtoMessage()    {}
func (*Rip) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{3}
}

func (m *Rip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rip.Unmarshal(m, b)
}
func (m *Rip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rip.Marshal(b, m, deterministic)
}
func (m *Rip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rip.Merge(m, src)
}
func (m *Rip) XXX_Size() int {
	return xxx_messageInfo_Rip.Size(m)
}
func (m *Rip) XXX_DiscardUnknown() {
	xxx_messageInfo_Rip.DiscardUnknown(m)
}

var xxx_messageInfo_Rip proto.InternalMessageInfo

func (m *Rip) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rip) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Rip) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type GetRippedResponse struct {
	Ripped               []*Rip   `protobuf:"bytes,1,rep,name=ripped,proto3" json:"ripped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRippedResponse) Reset()         { *m = GetRippedResponse{} }
func (m *GetRippedResponse) String() string { return proto.CompactTextString(m) }
func (*GetRippedResponse) ProtoMessage()    {}
func (*GetRippedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{4}
}

func (m *GetRippedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRippedResponse.Unmarshal(m, b)
}
func (m *GetRippedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRippedResponse.Marshal(b, m, deterministic)
}
func (m *GetRippedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRippedResponse.Merge(m, src)
}
func (m *GetRippedResponse) XXX_Size() int {
	return xxx_messageInfo_GetRippedResponse.Size(m)
}
func (m *GetRippedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRippedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRippedResponse proto.InternalMessageInfo

func (m *GetRippedResponse) GetRipped() []*Rip {
	if m != nil {
		return m.Ripped
	}
	return nil
}

type GetMissingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMissingRequest) Reset()         { *m = GetMissingRequest{} }
func (m *GetMissingRequest) String() string { return proto.CompactTextString(m) }
func (*GetMissingRequest) ProtoMessage()    {}
func (*GetMissingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{5}
}

func (m *GetMissingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMissingRequest.Unmarshal(m, b)
}
func (m *GetMissingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMissingRequest.Marshal(b, m, deterministic)
}
func (m *GetMissingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMissingRequest.Merge(m, src)
}
func (m *GetMissingRequest) XXX_Size() int {
	return xxx_messageInfo_GetMissingRequest.Size(m)
}
func (m *GetMissingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMissingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMissingRequest proto.InternalMessageInfo

type GetMissingResponse struct {
	Missing              []*proto1.Record `protobuf:"bytes,1,rep,name=missing,proto3" json:"missing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetMissingResponse) Reset()         { *m = GetMissingResponse{} }
func (m *GetMissingResponse) String() string { return proto.CompactTextString(m) }
func (*GetMissingResponse) ProtoMessage()    {}
func (*GetMissingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{6}
}

func (m *GetMissingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMissingResponse.Unmarshal(m, b)
}
func (m *GetMissingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMissingResponse.Marshal(b, m, deterministic)
}
func (m *GetMissingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMissingResponse.Merge(m, src)
}
func (m *GetMissingResponse) XXX_Size() int {
	return xxx_messageInfo_GetMissingResponse.Size(m)
}
func (m *GetMissingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMissingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMissingResponse proto.InternalMessageInfo

func (m *GetMissingResponse) GetMissing() []*proto1.Record {
	if m != nil {
		return m.Missing
	}
	return nil
}

type ForceRequest struct {
	Type                 ForceRequest_ForceType `protobuf:"varint,1,opt,name=type,proto3,enum=cdprocessor.ForceRequest_ForceType" json:"type,omitempty"`
	Id                   int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ForceRequest) Reset()         { *m = ForceRequest{} }
func (m *ForceRequest) String() string { return proto.CompactTextString(m) }
func (*ForceRequest) ProtoMessage()    {}
func (*ForceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{7}
}

func (m *ForceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceRequest.Unmarshal(m, b)
}
func (m *ForceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceRequest.Marshal(b, m, deterministic)
}
func (m *ForceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceRequest.Merge(m, src)
}
func (m *ForceRequest) XXX_Size() int {
	return xxx_messageInfo_ForceRequest.Size(m)
}
func (m *ForceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForceRequest proto.InternalMessageInfo

func (m *ForceRequest) GetType() ForceRequest_ForceType {
	if m != nil {
		return m.Type
	}
	return ForceRequest_UNKNOWN
}

func (m *ForceRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ForceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForceResponse) Reset()         { *m = ForceResponse{} }
func (m *ForceResponse) String() string { return proto.CompactTextString(m) }
func (*ForceResponse) ProtoMessage()    {}
func (*ForceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb0231462381e4, []int{8}
}

func (m *ForceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceResponse.Unmarshal(m, b)
}
func (m *ForceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceResponse.Marshal(b, m, deterministic)
}
func (m *ForceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceResponse.Merge(m, src)
}
func (m *ForceResponse) XXX_Size() int {
	return xxx_messageInfo_ForceResponse.Size(m)
}
func (m *ForceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cdprocessor.ForceRequest_ForceType", ForceRequest_ForceType_name, ForceRequest_ForceType_value)
	proto.RegisterType((*Config)(nil), "cdprocessor.Config")
	proto.RegisterMapType((map[int32]int64)(nil), "cdprocessor.Config.LastProcessTimeEntry")
	proto.RegisterType((*GetRippedRequest)(nil), "cdprocessor.GetRippedRequest")
	proto.RegisterType((*Track)(nil), "cdprocessor.Track")
	proto.RegisterType((*Rip)(nil), "cdprocessor.Rip")
	proto.RegisterType((*GetRippedResponse)(nil), "cdprocessor.GetRippedResponse")
	proto.RegisterType((*GetMissingRequest)(nil), "cdprocessor.GetMissingRequest")
	proto.RegisterType((*GetMissingResponse)(nil), "cdprocessor.GetMissingResponse")
	proto.RegisterType((*ForceRequest)(nil), "cdprocessor.ForceRequest")
	proto.RegisterType((*ForceResponse)(nil), "cdprocessor.ForceResponse")
}

func init() { proto.RegisterFile("cdprocessor.proto", fileDescriptor_f8eb0231462381e4) }

var fileDescriptor_f8eb0231462381e4 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x8e, 0xd2, 0x4e,
	0x14, 0xfe, 0x95, 0x2e, 0xec, 0x72, 0xd8, 0x1f, 0x0b, 0xe3, 0x5e, 0x74, 0x6b, 0x54, 0xac, 0x37,
	0xc4, 0x18, 0x48, 0xe0, 0x42, 0x63, 0xa2, 0x89, 0x22, 0xfe, 0xdb, 0x5d, 0x24, 0x23, 0x1b, 0x2f,
	0x49, 0x69, 0x67, 0x61, 0x42, 0xdb, 0x19, 0xa7, 0x03, 0x1b, 0x1e, 0xc0, 0x07, 0xf0, 0x15, 0x7c,
	0x3a, 0x1f, 0xc3, 0x74, 0x66, 0x58, 0x5b, 0x59, 0xee, 0x66, 0xbe, 0xef, 0x3b, 0xdf, 0x39, 0xe7,
	0xeb, 0x14, 0x9a, 0x41, 0xc8, 0x05, 0x0b, 0x48, 0x9a, 0x32, 0xd1, 0xe1, 0x82, 0x49, 0x86, 0x6a,
	0x39, 0xc8, 0x1d, 0xce, 0xa9, 0x5c, 0xac, 0x66, 0x9d, 0x80, 0xc5, 0xdd, 0x99, 0x60, 0x72, 0x41,
	0x44, 0xc4, 0xe6, 0x34, 0xe8, 0x0a, 0x12, 0x30, 0x11, 0x06, 0x2c, 0x8a, 0x48, 0x20, 0x29, 0x4b,
	0xba, 0xaa, 0x78, 0x07, 0xd6, 0x9e, 0xde, 0x2f, 0x0b, 0x2a, 0x03, 0x96, 0x5c, 0xd3, 0x39, 0x9a,
	0x40, 0x33, 0xf2, 0x53, 0x39, 0x35, 0x3d, 0xa6, 0x92, 0xc6, 0xc4, 0xb1, 0x5a, 0x76, 0xbb, 0xd6,
	0x6b, 0x77, 0xf2, 0xd3, 0x68, 0x7d, 0xe7, 0xc2, 0x4f, 0xe5, 0x58, 0x83, 0x13, 0x1a, 0x93, 0x61,
	0x22, 0xc5, 0x06, 0x9f, 0x44, 0x45, 0xd4, 0x7d, 0x0b, 0xa7, 0x77, 0x09, 0x51, 0x03, 0xec, 0x25,
	0xd9, 0x38, 0x56, 0xcb, 0x6a, 0x97, 0x71, 0x76, 0x44, 0xa7, 0x50, 0x5e, 0xfb, 0xd1, 0x8a, 0x38,
	0xa5, 0x96, 0xd5, 0xb6, 0xb1, 0xbe, 0xbc, 0x2c, 0xbd, 0xb0, 0x3c, 0x04, 0x8d, 0x0f, 0x44, 0x62,
	0xca, 0x39, 0x09, 0x31, 0xf9, 0xbe, 0x22, 0xa9, 0xf4, 0x7e, 0x5a, 0x50, 0x9e, 0x08, 0x3f, 0x58,
	0x22, 0x04, 0x07, 0x21, 0x4d, 0x97, 0x4e, 0x59, 0x59, 0xa9, 0x33, 0x7a, 0x0c, 0xc7, 0x32, 0x23,
	0xa7, 0xc9, 0x2a, 0x9e, 0x11, 0x61, 0xda, 0xd4, 0x14, 0x36, 0x52, 0x10, 0x3a, 0x83, 0xa3, 0x1b,
	0x7f, 0x3d, 0xe5, 0xbe, 0x5c, 0xa8, 0x8e, 0x55, 0x7c, 0x78, 0xe3, 0xaf, 0xc7, 0xbe, 0x5c, 0x64,
	0x54, 0xcc, 0xfb, 0x9a, 0xb2, 0x35, 0x15, 0xf3, 0xbe, 0xa2, 0xee, 0x43, 0xf5, 0x3a, 0xf2, 0x03,
	0xcd, 0x1d, 0x28, 0xee, 0x28, 0x03, 0x32, 0xd2, 0xbb, 0x02, 0x1b, 0x53, 0x8e, 0xea, 0x50, 0xa2,
	0xa1, 0x69, 0x59, 0xa2, 0x61, 0x36, 0x60, 0xae, 0x8b, 0x3a, 0xa3, 0xa7, 0x50, 0x51, 0xc3, 0xa4,
	0x8e, 0xad, 0x12, 0x46, 0x85, 0x84, 0xd5, 0x62, 0xd8, 0x28, 0xbc, 0x57, 0xd0, 0xcc, 0xad, 0x9f,
	0x72, 0x96, 0xa4, 0x04, 0xb5, 0xa1, 0x22, 0x14, 0x62, 0x3e, 0x51, 0xa3, 0x60, 0x80, 0x29, 0xc7,
	0x86, 0xf7, 0xee, 0xa9, 0xf2, 0x4b, 0x9a, 0xa6, 0x34, 0x99, 0x6f, 0xe3, 0xfb, 0x08, 0x28, 0x0f,
	0x1a, 0xd3, 0x1e, 0x1c, 0xc6, 0x1a, 0x32, 0xae, 0x4e, 0x67, 0xe7, 0xdd, 0x60, 0x05, 0xe0, 0xad,
	0xd0, 0xfb, 0x61, 0xc1, 0xf1, 0x7b, 0x26, 0x02, 0x62, 0xac, 0xd1, 0x73, 0x38, 0x90, 0x1b, 0x4e,
	0x54, 0x00, 0xf5, 0xde, 0x93, 0xc2, 0x5c, 0x79, 0xa1, 0xbe, 0x4c, 0x36, 0x9c, 0x60, 0x55, 0x60,
	0x72, 0x2b, 0x6d, 0x73, 0xf3, 0x9e, 0x41, 0xf5, 0x56, 0x82, 0x6a, 0x70, 0x78, 0x35, 0x3a, 0x1f,
	0x7d, 0xf9, 0x36, 0x6a, 0xfc, 0x87, 0x10, 0xd4, 0xf1, 0x70, 0x80, 0x87, 0x6f, 0x26, 0xc3, 0xe9,
	0xc5, 0xa7, 0xd1, 0xf9, 0xd7, 0x86, 0xe5, 0x9d, 0xc0, 0xff, 0xc6, 0x5d, 0x2f, 0xd3, 0xfb, 0x6d,
	0x41, 0x6d, 0xf0, 0x6e, 0xbc, 0xed, 0x8d, 0x3e, 0x43, 0xf5, 0x36, 0x46, 0xf4, 0xa0, 0x30, 0xd6,
	0xbf, 0xaf, 0xcb, 0x7d, 0xb8, 0x8f, 0x36, 0x41, 0x5d, 0x02, 0xfc, 0x8d, 0x0f, 0xed, 0xa8, 0x8b,
	0x61, 0xbb, 0x8f, 0xf6, 0xf2, 0xc6, 0xee, 0x35, 0x94, 0xd5, 0xec, 0xe8, 0x6c, 0x6f, 0x5a, 0xae,
	0x7b, 0x17, 0xa5, 0xeb, 0x67, 0x15, 0xf5, 0x33, 0xf7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x61,
	0x3a, 0x71, 0x3b, 0x35, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CDProcessorClient is the client API for CDProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CDProcessorClient interface {
	GetRipped(ctx context.Context, in *GetRippedRequest, opts ...grpc.CallOption) (*GetRippedResponse, error)
	GetMissing(ctx context.Context, in *GetMissingRequest, opts ...grpc.CallOption) (*GetMissingResponse, error)
	Force(ctx context.Context, in *ForceRequest, opts ...grpc.CallOption) (*ForceResponse, error)
}

type cDProcessorClient struct {
	cc *grpc.ClientConn
}

func NewCDProcessorClient(cc *grpc.ClientConn) CDProcessorClient {
	return &cDProcessorClient{cc}
}

func (c *cDProcessorClient) GetRipped(ctx context.Context, in *GetRippedRequest, opts ...grpc.CallOption) (*GetRippedResponse, error) {
	out := new(GetRippedResponse)
	err := c.cc.Invoke(ctx, "/cdprocessor.CDProcessor/GetRipped", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDProcessorClient) GetMissing(ctx context.Context, in *GetMissingRequest, opts ...grpc.CallOption) (*GetMissingResponse, error) {
	out := new(GetMissingResponse)
	err := c.cc.Invoke(ctx, "/cdprocessor.CDProcessor/GetMissing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDProcessorClient) Force(ctx context.Context, in *ForceRequest, opts ...grpc.CallOption) (*ForceResponse, error) {
	out := new(ForceResponse)
	err := c.cc.Invoke(ctx, "/cdprocessor.CDProcessor/Force", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDProcessorServer is the server API for CDProcessor service.
type CDProcessorServer interface {
	GetRipped(context.Context, *GetRippedRequest) (*GetRippedResponse, error)
	GetMissing(context.Context, *GetMissingRequest) (*GetMissingResponse, error)
	Force(context.Context, *ForceRequest) (*ForceResponse, error)
}

func RegisterCDProcessorServer(s *grpc.Server, srv CDProcessorServer) {
	s.RegisterService(&_CDProcessor_serviceDesc, srv)
}

func _CDProcessor_GetRipped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRippedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDProcessorServer).GetRipped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdprocessor.CDProcessor/GetRipped",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDProcessorServer).GetRipped(ctx, req.(*GetRippedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDProcessor_GetMissing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMissingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDProcessorServer).GetMissing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdprocessor.CDProcessor/GetMissing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDProcessorServer).GetMissing(ctx, req.(*GetMissingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDProcessor_Force_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDProcessorServer).Force(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdprocessor.CDProcessor/Force",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDProcessorServer).Force(ctx, req.(*ForceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CDProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdprocessor.CDProcessor",
	HandlerType: (*CDProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRipped",
			Handler:    _CDProcessor_GetRipped_Handler,
		},
		{
			MethodName: "GetMissing",
			Handler:    _CDProcessor_GetMissing_Handler,
		},
		{
			MethodName: "Force",
			Handler:    _CDProcessor_Force_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdprocessor.proto",
}
